### PR TITLE
remove underscore

### PR DESCRIPTION
**Pull request by macrozone**
fixes https://github.com/raix/Meteor-EventEmitter/issues/13

### CODE REVIEW

**Comment by sakulstra** [comment]
@raix any update on this? (just looking to improve our bundle size and realized this package is pulling in underscore)

**Comment by raix** [comment]
thanks @macrozone I'll try to get it released this weekend

**Comment by macrozone** [comment]
Hi @raix. Any chance to do the release soon? Thx!

**Comment by sakulstra** [comment]
@raix any update on this?

**Comment by raix** [comment]
@sakulstra @macrozone I've released it as v1.0.0

**Pull request merged**
